* Brightness control program for AGAN X230 2K modification board

There are exists some 2K modification boards (usually named Agan X230) for
Lenovo Thinkpad X220/X230: [[https://aliexpress.ru/item/1005004222503527.html][link]]. This program can change 2K display brightness
via board's USBHID interface.

*Program written only for FreeBSD.*

** Dependencies

- [[https://github.com/rpm-software-management/popt][libpopt]]
- [[https://github.com/libusb/hidapi][libhidapi]]

To build program =autotools= and =bash= is necessary.

** Compilation and installation

#+begin_example
./scripts/autotools.sh
./configure
make
sudo make install
#+end_example

Last command will install compiled binary and man page. Also, it will install
necessary devd rule to =/usr/local/etc/devd/agan.conf=.

After installation you can reboot computer to apply devd rule. Just a devd
restart will not work - because AGAN X230 board soldered to motherboard and
cannot be reconnected. New devd rule will be applied only on system startup.

User, which want to use this program, should be on the =wheel= group. If you
want to use another group — edit the =agan.conf= file.

** Usage

Brightness from AGAN X230 can take values from 0 to 15.

To read brightness from board just run:
#+begin_example
brightness_agan2k
#+end_example

To write brightness to board:
#+begin_example
brightness_agan2k -b 10
#+end_example

Or:
#+begin_example
brightness_agan2k --brightness 10
#+end_example
